function Rotate = Rotation(phi,theta,psi,a)
Rphi = [     1           0           0    ;...
             0        cos(phi)    -sin(phi);...
             0        sin(phi)    cos(phi)];               
Rtheta =[ cos(theta)     0        sin(theta);...
             0           1           0      ;...
         -sin(theta)     0        cos(theta)];
Rpsi = [  cos(psi)   -sin(psi)       0      ;...
          sin(psi)    cos(psi)       0      ;...
             0           0           1      ];
if a == 1
    Rotate = Rpsi*Rtheta*Rphi; %Rotations from Cargo or Platform to Earth fixed cs
elseif a == 2
    %yaw-pitch-roll sequence, 3-2-1 Euler Angle sequence!
    Rotate = Rphi'*Rtheta'*Rpsi'; %Rotations from Earth fixed to either Cargo or Platform cs, 3-2-1 Euler Angle
end

return;